### ISSUE TITLE
Resize Grid Error

### ISSUE THREAD

**Issue by beowulf005** [ryanlanegit/CustomGridTasks#1]
When Resizing the grid dev tool reports error:
Uncaught TypeError: Cannot read property 'field' of undefined
And then will clock. Refreshing the page clears the error and the grid retains the column adjustment.

**Comment by ryanlanegit** [comment]
This error was due to jQuery's Ajax request parsing all column objects and passing their contents as additional params on resizing.  I have disabled enumeration on the CustomGrid properties and added a '_' prefix so resizing should work properly.
